<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>index</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="index_files/libs/clipboard/clipboard.min.js"></script>
<script src="index_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="index_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="index_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="index_files/libs/quarto-html/popper.min.js"></script>
<script src="index_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="index_files/libs/quarto-html/anchor.min.js"></script>
<link href="index_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="index_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="index_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="index_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="index_files/libs/bootstrap/bootstrap-d6a003b94517c951b2d65075d42fb01b.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">




<p>x— title: “Simulation Challenge” subtitle: “Starter Template with To-Dos” format: html: default execute: echo: true eval: true —</p>
<section id="simulation-challenge---starter-template" class="level1">
<h1>🎲 Simulation Challenge - Starter Template</h1>
<div class="callout callout-style-default callout-important callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Important</span>📋 What You Need To Do
</div>
</div>
<div class="callout-body-container callout-body">
<ul class="task-list">
<li><label><input type="checkbox">Fork and create repo <code>simulationChallenge</code> in your GitHub</label></li>
<li><label><input type="checkbox">Clone locally and open in Cursor</label></li>
<li><label><input type="checkbox">Write your analysis in this <code>index.qmd</code></label></li>
<li><label><input type="checkbox">Render to HTML (<code>quarto render</code> or Render button)</label></li>
<li><label><input type="checkbox">Push HTML to your repo and enable GitHub Pages</label></li>
<li><label><input type="checkbox">Share your site: <code>https://[your-username].github.io/simulationChallenge/</code></label></li>
</ul>
</div>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Warning</span>⚠️ AI Partnership Required
</div>
</div>
<div class="callout-body-container callout-body">
<p>Use Cursor AI for speed, but ensure you understand and can explain the results in your own words. Verify cursor’s calculations as investment simulation is tricky.</p>
</div>
</div>
<section id="the-investment-game-brief" class="level2">
<h2 class="anchored" data-anchor-id="the-investment-game-brief">The Investment Game (Brief)</h2>
<p>You have the opportunity to buy-in to this game next week with $30,000. Your job is to analyze the potential outcomes of the game and communicate why or why you should not buy-in to the game.</p>
<p>Each year after buy-in you flip a fair coin:</p>
<ul>
<li>Heads: increase your account balance by 50%</li>
<li>Tails: decrease your account balance by 40%</li>
</ul>
<p>You play annually until age 75. Your mission is to analyze outcomes and communicate insights clearly.</p>
<section id="generative-dag-model-from-the-source-challenge" class="level3">
<h3 class="anchored" data-anchor-id="generative-dag-model-from-the-source-challenge">Generative DAG Model (from the source challenge)</h3>
<p>The following DAFT diagram shows the generative structure of the investment game over time.</p>
<div id="cell-fig-investment-dag" class="cell" data-execution_count="2">
<div class="cell-output cell-output-display">
<div id="fig-investment-dag" class="quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-investment-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="index_files/figure-html/fig-investment-dag-output-1.png" width="649" height="220" class="figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-investment-dag-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Generative DAG model for the investment game showing how wealth evolves over time through coin flips
</figcaption>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="analysis-tasks-fill-these-in" class="level2">
<h2 class="anchored" data-anchor-id="analysis-tasks-fill-these-in">Analysis Tasks (Fill These In)</h2>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
<span class="screen-reader-only">Note</span>Grading Scope
</div>
</div>
<div class="callout-body-container callout-body">
<ul>
<li>Sections 1–4: required and can earn up to 90% of the grade.</li>
<li>Sections 5–6: optional; strong, well-supported work here can bring your score up to 100%.</li>
</ul>
</div>
</div>
<section id="expected-value-after-1-flip" class="level3">
<h3 class="anchored" data-anchor-id="expected-value-after-1-flip">1) Expected Value After 1 Flip</h3>
<p>TODO: Explain whether the expected value of your account balance after one flip is &gt;, =, or &lt; $30,000. What is the gain in expected value as a percentage of your buy-in? Does this simple analysis suggest you should buy-in to the game?</p>
<div id="q1-expected-value-py" class="cell" data-execution_count="3">
<div class="cell-output cell-output-stdout">
<pre><code>Initial wealth: $30,000
After heads (50%): $45,000.0
After tails (50%): $18,000.0

Expected value after one flip: $31,500.00
Gain in EV: $1,500.00
Percentage gain: 5.00%</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong> The expected value after one flip is <strong>$31,500</strong>, which is <strong>5% higher</strong> than the initial buy-in of $30,000. This simple expected value calculation suggests the game has a positive expected return, which is favorable for the investor. However, this is based ona single flip and does not account for the volatility of the game over time.</p>
</section>
<section id="single-simulation-over-time-narrative-plot" class="level3">
<h3 class="anchored" data-anchor-id="single-simulation-over-time-narrative-plot">2) Single Simulation Over Time (Narrative + Plot)</h3>
<p>Briefly narrate and visualize what happens to your account balance over the course of one run. Are you happy with the outcome? Why? or Why not? You can use a time series plot to visualize the changes in your account balance over time.</p>
<div id="cell-q2-single-sim-py" class="cell" data-execution_count="4">
<div class="cell-output cell-output-display">
<div id="q2-single-sim-py" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/q2-single-sim-py-output-1.png" width="758" height="566" class="figure-img"></p>
<figcaption>Single simulation path of account balance</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Starting Age: 46
Final Age: 75
Number of flips: 29

Initial balance: $30,000
Final balance after 29 flips: $25,736.39
Total return: $-4,263.61 (-14.21%)
Peak balance: $79,433.31
Minimum balance: $3,826.38

Heads (wins): 8 out of 29 (27.59%)
Tails (losses): 21 out of 29 (72.41%)</code></pre>
</div>
</div>
<p><strong>Narrative:</strong> This simulation (with seed=42 for reproducibility) reveals a path of significant volatility in the account balance. The strategy generates dramatic swings with each coin flip, where the account can experience both rapid gains and substantial drawdowns. This illustrates the inherent risk and substantial uncertainty of the investment, as the account value is highly sensitive to the outcome of each individual event. While the theoretical expected value of the strategy is positive over an infinite number of trials, the observed single path demonstrates the stark reality that individual outcomes can vary widely and that a favorable long-term average does not mitigate the risk of significant short-term losses. This highlights the crucial distinction between a strategy’s expected value and the actual, high-variance results experienced in a finite number of simulations.</p>
</section>
<section id="simulations-distribution-of-final-balances" class="level3">
<h3 class="anchored" data-anchor-id="simulations-distribution-of-final-balances">3) 100 Simulations: Distribution of Final Balances</h3>
<p>TODO: Visually and narratively describe the distribution of your account balance after running the 100 simulations. What is the probability of outcomes that you’d be happy with after having invested $30,000?</p>
<div id="cell-q3-dist-100-py" class="cell" data-execution_count="5">
<div class="cell-output cell-output-display">
<div id="q3-dist-100-py" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/q3-dist-100-py-output-1.png" width="759" height="566" class="figure-img"></p>
<figcaption>Distribution of final balances across 100 simulations</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Simulation Parameters:
  --------------------------------
  Initial balance: $30,000
  Number of simulations: 100
  Time period: 29 (ages 46-75)

Distribution Statistics:
  --------------------------------
  Mean final balance: $192,131.11
  Median final balance: $10,294.56
  standard deviation: $1,561,309.44
  Minimum final balance: $16.87
  Maximum final balance: $15,708,246.77

Probability Statistics:
  --------------------------------
  Probability of final balance &lt; $30,000: 81.0%
  Probability of final balance &gt; $30,000: 19.0%</code></pre>
</div>
</div>
<p><strong>Narrative:</strong> After running 100 simulations of the game over 29 years:</p>
<p><strong>Distribution Characteristics:</strong></p>
<ul>
<li>The distribution is heavily right-skewed.</li>
<li>Mean balance is $192,131.11 which is significantly higher than the median balance of $10,294.56.</li>
<li>Standard deviation is $1,561,309.44 which is very high.</li>
<li>This indicates extreme volatility in the outcomes: some simulations end up with very high balances, while others end up with very low balances or significant losses.</li>
<li>The wide range (from $16.87 to $15,708,246.77) demonstrates the extreme nature of the outcomes &amp; high variance.</li>
</ul>
<p><strong>Probability of Happy Outcomes:</strong></p>
<ul>
<li>On investing $30,000, probability of ending with more than $30,000 is 19%.</li>
<li>This means in 19 out of 100 simulations would be considered a “happy outcome”.</li>
</ul>
<p><strong>Risk Assessment:</strong></p>
<ul>
<li>Less than 20% of the simulations ended with a balance greater than $30,000. This is a significant risk, as it means that the investor has a 20% chance of losing money over the 29-year period.</li>
<li>The high standard deviation of $1,561,309.44 indicates that the outcomes are highly unpredictaable.</li>
<li>You could loose up to $15,708,246.77 if the outcomes are very unfavorable or gain up to $192,131.11 if the outcomes are very favorable.</li>
</ul>
<p><strong>Conclusion:</strong></p>
<p>For an investor considering whether to buy into this game with $30,000, the simulation results suggest that:</p>
<ul>
<li>The probability of losing money is significant</li>
<li>The range of possible outcomes is extreme</li>
<li>The typical (median) outcome may be disappointing despite positive expected value</li>
<li>The risk of catastrophic loss cannot be ignored</li>
</ul>
<p>This analysis demonstrates why risk assessment must go beyond simple expected value calculations. The distribution characteristics, probability of favorable outcomes, and comprehensive risk assessment all point to the same conclusion: <strong>this investment, while mathematically favorable in expectation, carries substantial risk that may be unacceptable for most investors, particularly those who cannot afford to lose their initial capital.</strong></p>
</section>
<section id="probability-balance-30000-at-age-75-original-game" class="level3">
<h3 class="anchored" data-anchor-id="probability-balance-30000-at-age-75-original-game">4) Probability Balance &gt; $30,000 at Age 75 (Original Game)</h3>
<p>TODO: Report the probability estimate and interpret its practical meaning.</p>
<div id="q4-prob-original-py" class="cell" data-execution_count="6">
<div class="cell-output cell-output-stdout">
<pre><code>Probability estimate P(final &gt; $30,000): 19.0%</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<p>The probability estimate P(final &gt; $30,000) = 19.0% reveals a critical insight about the investment game’s risk profile. This means that out of 100 simulations, only approximately 19 end with a final balance greater than the initial $30,000 investment.</p>
<p><strong>Conclusion:</strong></p>
<p>The probability estimate of 19% for ending above the initial investment provides a clear, quantitative measure of the investment’s risk. This low probability, combined with the extreme volatility and wide range of outcomes observed in the simulations, suggests that <strong>this investment carries substantial risk that may be unacceptable for most investors</strong>. The practical meaning is clear: despite a positive expected value, an investor should expect to lose money in the majority of scenarios, making this a high-risk proposition that requires careful consideration of one’s risk tolerance and ability to withstand potential losses.</p>
</section>
<section id="modified-strategy-bet-exactly-50-each-round" class="level3">
<h3 class="anchored" data-anchor-id="modified-strategy-bet-exactly-50-each-round">5) Modified Strategy (Bet Exactly 50% Each Round)</h3>
<p>Instead of having the full balance at risk with each coin flip, assume only 50% of your balance is gambled each year. Compare this to the original game. Which is riskier? Which has better upside?</p>
<div id="cell-q5-modified-50pct-py" class="cell" data-execution_count="7">
<div class="cell-output cell-output-display">
<div id="q5-modified-50pct-py" class="quarto-figure quarto-figure-center anchored">
<figure class="figure">
<p><img src="index_files/figure-html/q5-modified-50pct-py-output-1.png" width="759" height="566" class="figure-img"></p>
<figcaption>Comparison of original and modified strategy distributions on the same plot</figcaption>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>============================================================
COMPARISON: Original vs Modified Strategy
============================================================

Original Strategy (Full Balance at Risk):
  Mean final balance: $192,131.11
  Median final balance: $10,294.56
  Standard deviation: $1,561,309.44
  P(final &gt; $30,000): 19.0%
  Min: $16.87, Max: $15,708,246.77

Modified Strategy (50% of Balance at Risk):
  Mean final balance: $59,692.16
  Median final balance: $37,500.00
  Standard deviation: $136,670.26
  P(final &gt; $30,000): 54.0%
  Min: $1,649.27, Max: $1,332,267.63

Differences:
  Mean difference: $-132,438.95
  Median difference: $27,205.44
  Standard dev ratio (mod/orig): 0.088
  P(&gt;$30,000) difference: 35.0%</code></pre>
</div>
</div>
<p><strong>Interpretation:</strong></p>
<p><strong>Which strategy is riskier?</strong></p>
<p>The <strong>original strategy (100% of balance at risk) is significantly riskier</strong> than the modified strategy. This is evident from several key metrics:</p>
<ol type="1">
<li><p><strong>Standard Deviation</strong>: The original strategy has a much higher standard deviation, indicating greater volatility and uncertainty in outcomes. The standard deviation ratio shows that the modified strategy has substantially less variability.</p></li>
<li><p><strong>Range of Outcomes</strong>: The original strategy exhibits a wider spread between minimum and maximum final balances, demonstrating extreme outcomes in both directions. This creates a higher risk of substantial losses.</p></li>
<li><p><strong>Probability of Loss</strong>: While both strategies have some probability of ending below the initial investment, the original strategy’s higher volatility means it has a greater chance of experiencing severe drawdowns.</p></li>
<li><p><strong>Median vs Mean</strong>: The larger gap between median and mean in the original strategy (compared to the modified strategy) indicates a right-skewed distribution with more extreme positive outliers, but also more potential for significant losses.</p></li>
</ol>
<p><strong>Which has better upside?</strong></p>
<p>The <strong>original strategy (100% of balance at risk) has better upside potential</strong>, as evidenced by:</p>
<ol type="1">
<li><p><strong>Higher Maximum Values</strong>: The original strategy achieves higher maximum final balances in the simulations, demonstrating its superior upside when favorable sequences of coin flips occur.</p></li>
<li><p><strong>Higher Mean</strong>: The original strategy has a higher mean final balance, reflecting its greater expected value when all outcomes are considered.</p></li>
<li><p><strong>Compounding Effect</strong>: By betting the full balance each round, the original strategy benefits more from compounding gains during winning streaks, leading to exponential growth in favorable scenarios.</p></li>
</ol>
<p><strong>Trade-off Summary:</strong></p>
<p>The comparison reveals a classic risk-return trade-off:</p>
<ul>
<li><strong>Original Strategy</strong>: Higher risk (volatility) but better upside potential (higher maximums and mean)</li>
<li><strong>Modified Strategy</strong>: Lower risk (reduced volatility) but more limited upside (lower maximums and mean)</li>
</ul>
<p>The modified strategy provides a more balanced approach, reducing the risk of catastrophic losses while still maintaining positive expected returns, though with less extreme upside potential. This makes it more suitable for risk-averse investors who prioritize capital preservation over maximum growth potential.</p>
</section>
<section id="briefly-explain-your-findings-from-the-previous-step-in-light-of-a-concept-known-as-the-kelly-criterion" class="level3">
<h3 class="anchored" data-anchor-id="briefly-explain-your-findings-from-the-previous-step-in-light-of-a-concept-known-as-the-kelly-criterion">6) Briefly Explain Your Findings From The Previous Step in Light of A Concept Known as the “Kelly Criterion”</h3>
<p>What is the Kelly Criterion and how does it relate to the modified strategy?</p>
<div id="q6-kelly-criterion-py" class="cell" data-execution_count="8">
<div class="cell-output cell-output-stdout">
<pre><code>======================================================================
KELLY CRITERION ANALYSIS
======================================================================

Game Parameters:
  Probability of win (p): 0.5
  Probability of loss (q): 0.5
  Win multiplier: 1.5x (gain 50% on bet)
  Loss multiplier: 0.6x (lose 40% on bet)
  Net gain on win (b): 0.5 (50% of fraction bet)
  Net loss on loss (a): 0.4 (40% of fraction bet)

Kelly Criterion Formula:
  f* = (p*b - (1-p)*a) / (b*a)
  f* = (0.5*0.5 - 0.5*0.4) / (0.5*0.4)
  f* = (0.250 - 0.200) / 0.200
  f* = 0.050 / 0.200
  f* = 0.250 (25.0%)

Interpretation:
  The optimal fraction to bet each round is 25.0% of current wealth.
  This maximizes the long-term logarithmic growth rate.

Comparison with Strategies:
  Original Strategy: 100% of balance at risk (over-betting)
  Modified Strategy: 50% of balance at risk (still over-betting)
  Kelly Optimal: 25.0% of balance at risk

  ✓ The game has positive expected value, so Kelly fraction is positive.
  ✓ Both strategies (100% and 50%) bet more than the Kelly optimal.
  ✓ Over-betting relative to Kelly increases volatility and risk of ruin.

======================================================================</code></pre>
</div>
</div>
<p><strong>Explanation:</strong></p>
<p>The <strong>Kelly Criterion</strong> is a formula that determines the optimal fraction of wealth to bet in order to maximize long-term logarithmic growth rate. Developed by John L. Kelly Jr.&nbsp;in 1956, it balances the trade-off between growth potential and risk of ruin.</p>
<p>For this investment game, the Kelly Criterion suggests betting approximately <strong>25%</strong> of your current wealth each round (f* = 0.25). This is calculated based on: - The probability of winning (50%) - The gain when winning (50% on the fraction bet) - The loss when losing (40% on the fraction bet)</p>
<p><strong>Key Findings:</strong></p>
<ol type="1">
<li><p><strong>Original Strategy (100% at risk)</strong>: This represents severe over-betting relative to the Kelly optimal. While it has the highest expected value and maximum upside potential, it also carries extreme volatility and a high risk of substantial losses. The geometric mean of returns is negative, meaning that despite a positive arithmetic mean, the strategy tends to lose money over the long run due to the asymmetry of multiplicative returns.</p></li>
<li><p><strong>Modified Strategy (50% at risk)</strong>: This strategy reduces risk compared to the original, but still over-bets relative to Kelly. It provides a better balance between growth and risk, with:</p>
<ul>
<li>Lower volatility than the original strategy</li>
<li>Higher probability of ending above the initial investment</li>
<li>Better median outcomes</li>
<li>Reduced risk of extreme losses</li>
</ul></li>
<li><p><strong>Kelly Optimal (25% at risk)</strong>: Betting the Kelly fraction would theoretically maximize long-term growth while minimizing the risk of ruin. It balances the trade-off between:</p>
<ul>
<li>Growth potential (higher expected logarithmic return)</li>
<li>Risk management (lower probability of catastrophic losses)</li>
<li>Volatility reduction (more stable outcomes)</li>
</ul></li>
</ol>
<p><strong>Practical Implications:</strong></p>
<p>The comparison between the original and modified strategies illustrates a fundamental principle: <strong>over-betting relative to Kelly increases both volatility and the risk of ruin, even when the expected value is positive</strong>. The modified strategy (50% betting) moves in the right direction toward the Kelly optimal but still carries more risk than necessary.</p>
<p>This analysis highlights why expected value alone is insufficient for decision-making in multiplicative (compounding) scenarios. The Kelly Criterion provides a framework for optimal capital allocation that accounts for both the probability and magnitude of outcomes, helping investors avoid the trap of over-leveraging even in favorable games.</p>
</section>
</section>
<section id="professional-presentation-from-grading-tldr" class="level2">
<h2 class="anchored" data-anchor-id="professional-presentation-from-grading-tldr">Professional Presentation (From Grading TLDR)</h2>
<ul>
<li><strong>Clear narrative:</strong> tell the story succinctly (aim for a 1–5 minute read)</li>
<li><strong>Focus on insights:</strong> risk profiles, counter-intuitive results, practical implications</li>
<li><strong>Professional style:</strong> concise writing, clean visuals, hide code where appropriate (<code>echo: false</code>)</li>
<li><strong>Human interpretation:</strong> explain what results mean for real decisions</li>
</ul>
</section>
<section id="submission-checklist" class="level2">
<h2 class="anchored" data-anchor-id="submission-checklist">Submission Checklist ✅</h2>
<ul class="task-list">
<li><label><input type="checkbox">Quarto document written with narrative and results</label></li>
<li><label><input type="checkbox">Rendered to HTML successfully</label></li>
<li><label><input type="checkbox">Repository <code>simulationChallenge</code> created on GitHub</label></li>
<li><label><input type="checkbox">HTML committed and pushed</label></li>
<li><label><input type="checkbox">GitHub Pages enabled (Deploy from a branch → main → /(root))</label></li>
<li><label><input type="checkbox">Site accessible at <code>https://[your-username].github.io/simulationChallenge/</code></label></li>
</ul>
</section>
<section id="tips" class="level2">
<h2 class="anchored" data-anchor-id="tips">Tips</h2>
<ul>
<li>Set random seeds for reproducibility</li>
<li>Use object-oriented plotting with <code>matplotlib</code></li>
<li>Keep figures readable and labeled; prefer professional styling</li>
<li>Commit early and often; render locally before pushing</li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>